version: '3.2'

services:
  postgres:
    restart: unless-stopped
    image: postgres:12
    hostname: postgres
    container_name: kailona-fhir-server_db
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fhirdb
      POSTGRES_USER: fhirserver
      POSTGRES_PASSWORD: change-postgres-password
  fhir-schematool:
    restart: on-failure
    image: ibmcom/ibm-fhir-schematool:4.7.0
    container_name: kailona-fhir-schematool
    environment:
      ENV_SKIP: "false" # Set to true if you want to manage postgres schema yourself (or once schema is initialized)
    command: --tool.behavior=onboard --db.type=postgresql --db.host=postgres --db.port=5432 --db.database=fhirdb --sslConnection=false --grant.to=fhirserver --user=fhirserver --password=change-postgres-password
    depends_on:
      - postgres
  fhir:
    restart: unless-stopped
    image: ibmcom/ibm-fhir-server:4.7.0
    hostname: fhir
    container_name: kailona-fhir-server
    volumes:
      - ./config:/opt/ol/wlp/usr/servers/defaultServer/config
      - ./overrides:/opt/ol/wlp/usr/servers/defaultServer/configDropins/overrides
    environment:
      FHIR_USER_PASSWORD: change-user-password
      FHIR_ADMIN_PASSWORD: change-admin-password
    ports:
      - 9080:9080
    depends_on:
      - postgres
